### PR TITLE
Fix the badge with a different method using camo.githubusercontent.com

### PR DESCRIPTION
**Pull request by 3prm3**
Image from https://camo.githubusercontent.com/07622e6662ef5ead080c4840ef6514a34e079d63015f7e51c977a55b1881dfb9/687474703a2f2f63662e776179326d7563686e6f6973652e65752f7469746c652f63632d726573746974636865642e737667

### CODE REVIEW

**Comment by 3prm3** [comment]
the method I used earlier seemed to fail so I redid this using the image from the last commit with it working

**Comment by SquidDev** [comment]
GitHub doesn't like the badge server's certificate - switching it back to http should work. Alternatively, might be worth embedding the badge in the repository - probably what I'll do for CC:T.

**Comment by 3prm3** [comment]
image
it works on my fork

**Comment by Merith-TK** [comment]
Im probably gonna just do what squid dev suggested (thanks for bringing this issue up tho!)

**Comment by 3prm3** [comment]
Both http and https seem to work
image

**Comment by 3prm3** [comment]
> GitHub doesn't like the badge server's certificate - switching it back to http should work. Alternatively, might be worth embedding the badge in the repository - probably what I'll do for CC:T.

By embedding do you mean adding the image as a file in the repo or something else

**Pull request merged**
