### PR TITLE
Properly implement turtle.getItemDetails()

### LINKED ISSUE #41: turtle.getItemDetail with advanced flag does not return extra data
# User Information
Minecraft version: 1.16.5
CC:R version: 1.95.3

# Bug Information

In CC:T, running `turtle.getItemDetail(anySlot, true)` should give more advanced data about an item, including some nbt data for some things. However, this does not happen, and it returns the exact same result to `turtle.getItemDetail(anySlot)`.

# Images

unknown-61
unknown-63

The above images should have a lot more data, including a `displayName` field.

# Links
[The beginning of the short discussion on discord.](https://discord.com/channels/477910221872824320/477911902152949771/847608698699513856)

### PR DESCRIPTION
**Pull request by hugeblank**
Fixes #41

Full parity would look like this:
image

The one and only missing field at the moment is `tags`, which I'm not sure exactly how to get.

### CODE REVIEW

**Comment by Merith-TK** [comment]
Once you get the tags I will merge, (unless they prove impossible?)

**Comment by hugeblank** [comment]
> 
> 
> Once you get the tags I will merge, (unless they prove impossible?)

Definitely not impossible! Just a really *really* dumb solution on mojangs part. I don't understand why they need an entire tag holder for the server when it could just be a static thing in the tag registry, ugh. 

It is ready for merge however! 🎉

**Comment by Merith-TK** [comment]
Can you screenshot that it does indeed work in CC:R?

**Comment by hugeblank** [comment]
Sure:
image
I posted it in the MC Computer Mods discord prior to this

**Pull request merged**
