### PR TITLE
Fix Disk Drive & Disk Interaction

### LINKED ISSUE #12: Shift right click to insert disk into disk drive doesn't work
It works on the forge version.

Code that isn't working: https://github.com/Merith-TK/cc-restitched/blob/9b77a4aaeecf4009151533600a442133e3181144/src/main/java/dan200/computercraft/shared/peripheral/diskdrive/TileDiskDrive.java#L74-L84

### PR DESCRIPTION
**Pull request by hugeblank**
Inject Special case into `ServerPlayerInteractionManager` that handles disks being sneak + right clicked onto disk drives.

Fixes #12

### CODE REVIEW

**Comment by Merith-TK** [comment]
does this work for both putting the disk in, and getting the disk out? also does it work with music discs?

**Comment by hugeblank** [comment]
> does this work for both putting the disk in, and getting the disk out?

It does not work for getting disks out, is something that CC:T does? If I could get confirmation on that then I'll get to working on that.

> also does it work with music discs?

Ooh, yeah I missed that. Will fix once I get clarification on the first concern above.

**Comment by Merith-TK** [comment]
Just tested myself, music discs dont work for it at all, and shift-right clicking does not eject

**Comment by hugeblank** [comment]
This meaning that this commit is good for a merge? Or do you think it would be a good idea to add support for disks?

**Comment by Merith-TK** [comment]
It is good to merge after some testing on my end of course

**Comment by Jummit** [comment]
There is no need for mixins to allow for disks to be injected into disk drives. Although I i think they are necessary to make it work with music discs.

**Comment by hugeblank** [comment]
> 
> 
> There is no need for mixins to allow disks to be injected into disk drives.
> See how I did it in [Jummit@6f70ebe](https://github.com/Jummit/cc-restitched/commit/6f70ebeb6ca93612ab2a85c0710af3bf1f149658)
> Although I i think they are necessary to make it work with music discs.

You're right, there was definitely a smarter approach than this but it accidentally worked out since for parity music discs need to be inserted like floppy disks anyways, as you mention. I'd rather keep it as one mixin than a mixin and a method in another class, for ease of reading.

**Comment by Jummit** [comment]
Don't forget to allow inserting portable computers.

**Comment by hugeblank** [comment]
> 
> 
> Don't forget to allow inserting portable computers.

good catch! I'll add this soon™️

**Pull request merged**
